config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  post 'show'=>'dashboard#show', as: :show

  resources :users
  match 'login'=>'users#login', via: [ :get, :post ], as: :login
  get 'logout'=>'users#logout', as: :logout


  get 'accounts/refresh'=>'accounts#refresh', as: :refresh_accounts
  resources :accounts

  post 'tokens/request'=>'tokens#request_token', as: :request_token
  post 'tokens/request/mfa'=>'tokens#request_mfa_code', as: :request_mfa_code
  post 'tokens/submit/mfa'=>'tokens#submit_mfa_code', as: :submit_mfa_code
  resources :tokens

  get  'widgets'=>'widgets#index', as: :widgets
  get  'widget/:name/add'=>'widgets#add', as: :add_widget
  post 'widget/:name/add'=>'widgets#configure', as: :configure_widget



end

app/models/widget.rb
class Widget < ActiveRecord::Base

  belongs_to :user

  validates :user_id, presence: true

  serialize :data, JSON

  def url_name
    type.split('::').last.paramify
  end

end

app/models/widget/account_balance.rb
class Widget::AccountBalance < Widget

  def name
    "Account Balance Widget"
  end

  def refresh_data
    get_plaid_data
  end

  def self.available_accounts(u)
    Plaid.customer.get_all(u)
  end


end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController

  def index

  end

  def add
    @widget = Widget.new(type: "Widget::#{params[:name].typify}")
  end

  def configure

  end

end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/widgets/_empty.html.erb
<div class="empty-widget well">
  <h1>Empty Widget</h1>
</div>

app/views/widgets/add.html.erb
<h1>Add <%= @widget.name %></h1>

<%= form_tag configure_widget_path(@widget.url_name) do %>

  <%= render partial: "widgets/forms/#{params[:name].underscore}" %>

  <%= submit_tag 'Save Changes', name: 'save', class: 'btn btn-primary' %>
<% end %>

app/views/widgets/index.html.erb
<h1><i class="glyphicon glyphicon-dashboard"></i> Widgets</h1>

<div class="row">
  <div class="col-md-6">
    <div class="well">
      <%= link_to add_widget_path('account-balance'), class: 'btn btn-primary pull-right' do %>
        <i class="glyphicon glyphicon-plus"></i> Add
      <% end %>
      <h3>Account Balance</h3>
      <p>Display your account balance</p>
    </div>
  </div>
  <div class="col-md-6">
  </div>
</div>