config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  post 'show'=>'dashboard#show', as: :show

  resources :users
  match 'login'=>'users#login', via: [ :get, :post ], as: :login
  get 'logout'=>'users#logout', as: :logout


  get 'accounts/refresh'=>'accounts#refresh', as: :refresh_accounts
  resources :accounts

  post 'tokens/request'=>'tokens#request_token', as: :request_token
  post 'tokens/request/mfa'=>'tokens#request_mfa_code', as: :request_mfa_code
  post 'tokens/submit/mfa'=>'tokens#submit_mfa_code', as: :submit_mfa_code
  resources :tokens

  get  'widgets'=>'widgets#index', as: :widgets
  get  'widget/:name/add'=>'widgets#add', as: :add_widget
  post 'widget/:name/add'=>'widgets#configure', as: :configure_widget



end

app/views/tokens/mfa/code/delivery_method.html.erb
<h1>Your bank uses a 2-Step verification system.</h1>
<h3>Choose delivery method:</h3>
<%= form_tag request_mfa_code_path do %>
  <% @response['mfa'].each do |mfa| %>
    <div class="radio">
      <%= label_tag mfa['type'] do %>
        <%= radio_button_tag "delivery", mfa['mask'], (mfa['type']=="email") %>
        <%= mfa['mask'] %>
      <% end %>
    </div>
  <% end %>
  <%= hidden_field_tag "institution", @institution %>
  <%= hidden_field_tag "access_token", @response['access_token'] %>
  <%= submit_tag 'Continue', class: 'btn btn-primary' %>
<% end %>

app/views/tokens/mfa/code/enter_code.html.erb
<h1><%= @response['mfa']['message'] %></h1>
<%= form_tag submit_mfa_code_path do %>
  <div class="form-group">
    <%= text_field_tag "code", nil, class: 'form-control', placeholder: 'Verification Code' %>
  </div>
  <%= hidden_field_tag "institution", @institution %>
  <%= hidden_field_tag "access_token", @response['access_token'] %>
  <%= submit_tag 'Continue', class: 'btn btn-primary' %>
<% end %>