config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  post 'show'=>'dashboard#show', as: :show

  resources :users
  match 'login'=>'users#login', via: [ :get, :post ], as: :login
  get 'logout'=>'users#logout', as: :logout


  get 'accounts/refresh'=>'accounts#refresh', as: :refresh_accounts
  resources :accounts

  post 'tokens/request'=>'tokens#request_token', as: :request_token
  post 'tokens/request/mfa'=>'tokens#request_mfa_code', as: :request_mfa_code
  post 'tokens/submit/mfa'=>'tokens#submit_mfa_code', as: :submit_mfa_code
  resources :tokens

  get  'widgets'=>'widgets#index', as: :widgets
  get  'widget/:name/add'=>'widgets#add', as: :add_widget
  post 'widget/:name/add'=>'widgets#configure', as: :configure_widget



end

app/views/layouts/_errors.html.erb
<% if klass.errors.any? %>
  <div class="alert alert-danger">
    <h4>There are <%= klass.errors.count %> <%= "problems".pluralize(klass.errors.count) %> with the form:</h4>
    <ul>
      <% klass.errors.each do |field, error| %>
        <li><%= field.to_s.humanize %> <%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="flash <%= flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value.html_safe %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Finances</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href='http://fonts.googleapis.com/css?family=Bitter:400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="application <%= "#{controller.controller_path.split('/').join(' ')} #{controller.action_name.gsub(/_/, '-')}" %>">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">My Finances</a>
        </div>
        <div class="navbar-login">
          <% unless current_user %>
            <ul>
              <li><%= link_to "Log In", login_path %></li>
            </ul>
          <% else %>
            <ul>
              <li>
                <%= link_to(root_path, class: 'white') do %>
                  <%= current_user.name %> <i class="glyphicon glyphicon-cog"></i>
                <% end %>
              </li>
              <li><span class="separator"></span></li>
              <li><%= link_to 'Log out', logout_path %></li>
            </ul>
          <% end  %>
        </div>
        <% if current_user %>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="<%= 'active' if is_controller?('accounts') || is_controller?('tokens') %>"><%= link_to 'Accounts', accounts_path %></li>
              <li class="<%= 'active' if is_controller?('widgets') %>"><%= link_to 'Widgets', widgets_path %></li>
            </ul>
          </div>
        <% end %>
      </div>
    </div>

    <div class="container content-section">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>

  </body>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</html>
\