config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  post 'show'=>'dashboard#show', as: :show

  resources :users
  match 'login'=>'users#login', via: [ :get, :post ], as: :login
  get 'logout'=>'users#logout', as: :logout


  get 'accounts/refresh'=>'accounts#refresh', as: :refresh_accounts
  resources :accounts

  post 'tokens/request'=>'tokens#request_token', as: :request_token
  post 'tokens/request/mfa'=>'tokens#request_mfa_code', as: :request_mfa_code
  post 'tokens/submit/mfa'=>'tokens#submit_mfa_code', as: :submit_mfa_code
  resources :tokens

  get  'widgets'=>'widgets#index', as: :widgets
  get  'widget/:name/add'=>'widgets#add', as: :add_widget
  post 'widget/:name/add'=>'widgets#configure', as: :configure_widget



end

app/models/account.rb
class Account < ActiveRecord::Base

  belongs_to :user
  belongs_to :token

  validates :service, presence: true
  validates :data, presence: true

  serialize :data, JSON

  PLAID = {
    "amex" => "American Express",
    "bofa" => "Bank of America",
    "capone360" => "Capital One 360",
    "schwab" => "Charles Schwab",
    "chase" => "Chase",
    "citi" => "Citi",
    "fidelity" => "Fidelity",
    "usaa" => "USAA",
    "us" => "US Bank",
    "wells" => "Wells Fargo"
  }

  def name
    self[:name] || case service
    when "plaid" then data['meta']['name']
    end.strip
  end

  def type
    case service
    when "plaid" then "#{data['type']} #{data['subtype']}"
    end.strip
  end

  def number
    case service
    when "plaid" then data['meta']['number']
    end.strip
  end

  def balance
    case service
    when "plaid" then data['balance']
    end
  end

  def institution_name
    PLAID[token.institution] if token
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @accounts = current_user.accounts
  end

  def refresh
    i = 0
    current_user.tokens.each do |token|
      options = {
        client_id: SECRETS[:plaid][:client_id],
        secret: SECRETS[:plaid][:secret],
        access_token: token.access_token
      }

      Rails.logger.debug "================================================================================"
      Rails.logger.debug options.inspect
      Rails.logger.debug "================================================================================"

      response = RestClient.get "https://tartan.plaid.com/connect", params: options
      @response = JSON.parse(response)

      Rails.logger.debug "================================================================================"
      Rails.logger.debug @response.inspect
      Rails.logger.debug "================================================================================"

      if @response.has_key?('accounts')
        @response['accounts'].each do |account_data|
          account = Account.find_by_service_id(service_id: account_data['_id'])
          account.data = account_data
          i+=1 if account.save
        end
      end
    end
    flash[:success] = "#{i} accounts updated successfully!"
    redirect_to accounts_path
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/index.html.erb
<h1><i class="glyphicon glyphicon-link"></i> Accounts</h1>

<div class="btn-group-separate">
  <%= link_to new_token_path, class: 'btn btn-primary' do %>
    <i class="glyphicon glyphicon-plus"></i> <strong>New</strong>
  <% end %>

  <% unless @accounts.empty? %>
    <%= link_to refresh_accounts_path, class: 'btn btn-warning' do %>
      <i class="glyphicon glyphicon-refresh"></i> <strong>Refresh Account Data</strong>
    <% end %>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Institution</th>
      <th>Name</th>
      <th>Type</th>
      <th>Number</th>
      <th>Balance</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.institution_name %></td>
        <td><%= account.name %></td>
        <td><%= account.type %></td>
        <td><%= account.number %></td>
        <td><%= account.balance %></td>
        <td>blah</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/accounts/new.html.erb
<h1>Add Account</h1>

<%= form_for @account do |f| %>
  <div class="form-group">
    <%= f.label :bank %>
    <%= f.select :bank, Account::PLAID, {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :username %>
    <%= f.text_field :username, class: 'form-control', placeholder: 'Username' %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>

  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
  </div>
  <%= f.submit 'Submit', class: 'btn btn-default' %>
<% end %>